### ISSUE TITLE
Permettre l'écriture de scénarios

### ISSUE THREAD

**Issue by BrunoForest** [Bureau-du-Forestier-en-chef/FMT#109]
Permettre l'écriture de plusieurs FMTmodel où les sections identiques sont à la racine et où pour chaque FMTmodel, un dossier avec le nom est écrit dans le sous-dossier Scenarios. Ce dossier contiendra les sections du modèle qui sont différente des sections à la racine.

**Comment by gcyr** [comment]
Fonction FMTmodelparser::writeproject(const std::string& localisation,const std::vector<Models::FMTmodel>& models,std::string filename= "ROOT"  )
