### ISSUE TITLE
ArgumentError LPModel.getvariabilities() - Exemple 1

### ISSUE THREAD

**Issue by pierre-cantegril** [Bureau-du-Forestier-en-chef/FMT#124]
Lorsque j'exécute le code solution de l'[exercice 1](https://bureau-du-forestier-en-chef.github.io/FMTdocs/fr/docs/basics/exercice_1/), la méthode `LPModel.getvariabilities([output])` renvoie l'erreur suivante : 
```
ArgumentError: Python argument types in
    FMTlpmodel.getvariabilities(FMTlpmodel, list)
did not match C++ signature:
    getvariabilities(class Models::FMTlpmodel {lvalue}, class std::vector<class Core::FMToutput,class std::allocator<class Core::FMToutput> >, int, int)
```

Il semblerait qu'il faille ajouter deux entiers à la fonction (?? et nombre de période) :

```
# On affiche les mesures de "OSUPREC" dans le terminal
print(LPModel.getvariabilities([output], 1, 10))
# On sauvegarde les valeurs de OSUPREC pour les mettre au propre ensuite
osuprecValues = LPModel.getvariabilities([output], 1, 10)
```

**Comment by BrunoForest** [comment]
En effet, la fonction a changé depuis que nous avons fait la page d'exercice. Nous allons mettre le tout à jour. La fonction FMTlpmodel.getvariabilities() prend une liste de FMToutput et deux entiers qui représentent la période de départ et de fin. 

Pour chaque période entre la période de départ et de fin, la fonction renverra la valeur minimale et maximale que le FMToutput peut prendre. Voici un lien vers la documentation Doxygen de la fonction en C++.
