### ISSUE TITLE
Ajouter un test pour le nouveau modèle protoype pour presolvetest

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#184]
Ajouter un test dans le fichier .csv de BFECtest en respectant les arguments pour le scénario rendement soutenue pour un horizon de 5 périodes. S'assurer que le tests créé passe merger si il passe sinon on cherche le trouble.

**Comment by gcyr** [comment]
Aussi tester testmodelwriter.cpp

**Comment by Landry-G** [comment]
Pull du master de FMT

Faire un dossier sous T:\Donnees\02_Courant\07_Outil_moyen_methode\01_Entretien_developpement\09_FMT\Modeles_test

Prendre les données de louis du courriel

Faire un test dans FMT pour ce modèle (à rajouter dans FMT)
	Faire un nouvelle branche (ex ajout test modèle prototype)

Mettre a jour ce que j'ai sur le D avec ce qu'il y a sur artemis
D:\Programation\FMTproject\FMT\Examples\C++\tests

02_Sc0_Rend_sout
