### ISSUE TITLE
Permettre la génération de schedule de replanning

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#220]
Conserver l'ensemble des schedules du replanning par modèle...Stratégique/sotchastique/opérationnel

**Comment by gcyr** [comment]
Dans la fonction FMTreplanningtask::writeresults à partir du pointeur vers le modèle appeller Core::FMTschedule FMTmodel::getsolution(int period, bool withlock = false) const pour la période de replanification actuel du modèle et ce seulement lors de l'écriture du modèle stochastique et tactique voir FMTreplanningtask::work() et FMTreplanningtask::domodelplanning() pour voir l'utilisation de FMTreplanningtask::writeresults. Voir FMTscheduleparser::write et développer une fonction FMTscheduleparser::append qui permet d'écrire une cédule dans un fichier d'éjà existant. Pour permettre d'écrire dans un même fichier schedule un réplicat donné pour toute les périodes de replanification et les modèles tactique et stochastique. Identifier les noms des cédules à l'aide du réplicat et du nom du modèle (faire un string) avec FMTmodel::getname() + getiteration() +".seq" = nom du fichier schedule. Finalement ajouter une méthode au FMTreplanningtask public du genre setScheduleWrite(true) pour indiquer à la task quelle doit écrire la cédule du modèle.

**Comment by gcyr** [comment]
Développer un test en extensionnant replanner.cpp pour tester l'écriture des solutions des réplicats et par la suite lire au moins un réplicat et le réinterpréter voir FMTsetsolution.cpp pour monter le test.

**Comment by gcyr** [comment]
Modifier Wrapper::FMTForm::Replanification pour tenir compte de la nouvelle option d'écriture du de la cédule et valider sont bon fonctionnement (bonifier le unit test de FMTForm).

**Comment by Landry-G** [comment]
**Conserver l'ensemble des schedules du replanning par modèle Stratégique/sotchastique/opérationnel**

1. Aller dans la fonction  FMTreplanningtask::writeresults pour accèder au pointeur Core::FMTschedule FMTmodel::getsolution(int period, bool withlock = false) const
2. On a un exemple de stocastique et tactique en en allant voir FMTreplanningtask::work() et FMTreplanningtask::domodelplanning() pour voir l'utilisation de FMTreplanningtask::writeresults
3. AJouter la fonction FMTscheduleparser::append dans FMTscheduleparser::write. Cela permet d'écrire dans un même fichier schedule un réplicat donné pour toute les périodes de replanification et les modèles tactique et stochastique.
4. Grâce à FMTmodel::getname(), accéder au nom des cédules et l'itération avec getiteration() pour écrire un fichier schedule (FMTmodel::getname() + getiteration() +".seq" = nom du fichier schedule)
5. Finalement ajouter une méthode au FMTreplanningtask public du genre setScheduleWrite(true) pour indiquer à la task quelle doit écrire la cédule du modèle.

* Développer un test en extensionnant replanner.cpp pour tester l'écriture des solutions des réplicats et par la suite lire au moins un réplicat et le réinterpréter voir FMTsetsolution.cpp pour monter le test.

* Modifier Wrapper::FMTForm::Replanification pour tenir compte de la nouvelle option d'écriture du de la cédule et valider sont bon fonctionnement (bonifier le unit test de FMTForm). 
   * Consiste à fournir un argument pour que Tommy l'intègre de son côté avec les cases à cocher


1. Prendre en exemple les lignes 183 à 214 dans FMTscheduleparser 
2. Regarder la possibilité de faire une méthode privée en ofstream?? du genre _write(const std::vectorCore::FMTschedule& p_schedules, std::ofstream p_stream) const;
3. Par la suite, ajouter la fonction dans FMTscheduleparser::write et dans FMTscheduleparser::append
4. Regarder la possibilité de faire un bool à la fonction write (possibilité pour ne pas avoir à écrire une nouvelle méthode)
5. FInalement, faire un test de lecture (comme en exemple le test replanner.cpp voir plus haut).

**Comment by martel21324** [comment]
Objectif
Permettre la génération de plannings de replanning et conserver l'ensemble des plannings de replanning par modèle : stratégique, stochastique, et opérationnel.

Tâches à réaliser

- [ ] Modification de FMTreplanningtask::writeresults :

Utiliser le pointeur vers le modèle pour appeler Core::FMTschedule FMTmodel::getsolution(int period, bool withlock = false) const afin d'obtenir la solution pour la période de replanification actuelle.

[ ] - Trouver comment appliquer cette méthode uniquement lors de l'écriture des modèles stochastique et tactique.

tips : Références : Voir FMTreplanningtask::work() et FMTreplanningtask::domodelplanning() pour l'utilisation de FMTreplanningtask::writeresults.

[ ] - Développement de la fonction FMTscheduleparser::append :

Cette fonction permettra d'écrire un planning dans un fichier déjà existant.
Écrire les plannings de tous les réplicats pour toutes les périodes de replanification et pour les modèles tactique et stochastique dans un même fichier.
[ ] - Trouver comment nommé les replanning si besoin. Identifier les noms des plannings en utilisant le réplicat et le nom du modèle (FMTmodel::getname() + getiteration() + ".seq").


[ ] - Ajout d'une méthode publique à FMTreplanningtask :
Ajouter une méthode telle que setScheduleWrite(true) pour indiquer à la tâche d'écrire le planning du modèle.
Développement et extension de tests :

[ ] - Étendre replanner.cpp pour tester l'écriture des solutions des réplicats et la lecture d'au moins un réplicat.
Références : Voir FMTsetsolution.cpp pour élaborer le test.

[ ] - Modification de Wrapper::FMTForm::Replanification :
Prendre en compte la nouvelle option d'écriture du planning et valider son bon fonctionnement en bonifiant le test unitaire de FMTForm.

Cette partie est terminé, nou avons ajouter l'option dans le ofstream pour append avec des vérification avant.
Méthode recommandée pour FMTreplanningtask::append
Développer la méthode FMTreplanningtask::append(const std::vector<Core::FMTschedule>& p_schedules, const std::string& p_location) const en suivant ces étapes :

Créer une méthode privée _write(const std::vector<Core::FMTschedule>& p_schedules, std::ofstream p_stream) const.
Utiliser les lignes 183 à 214 de FMTscheduleparser pour construire cette fonction.
Appeler cette fonction dans FMTscheduleparser::write et FMTscheduleparser::append.
Envisager d'ajouter un booléen à la fonction write selon votre préférence.
Développer un test de lecture-écriture pour cette fonction.

**Comment by martel21324** [comment]
Erreur lors du lancement du replanner avec 5 threads:
![image](https://github.com/user-attachments/assets/38badea8-52ea-4a32-a7c7-c543ca93a0a3)

**Comment by gcyr** [comment]
Bad allocation c'est un manque de mémoire c'est quoi les paramètres d'entré du test?

**Comment by martel21324** [comment]
![image](https://github.com/user-attachments/assets/d9cbe1a4-4392-48bf-9059-d1fec8caf91b)
![image](https://github.com/user-attachments/assets/2cb38ebd-fdde-44fb-8277-968578f8193a)

**Comment by martel21324** [comment]
Tous les test fonctionnent et l'écriture se fait correctement.
