### ISSUE TITLE
Développer une fonction de requète de yield dans FMTwrapper

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#222]
Développer une fonction de requète de yield dans FMTForm.h /.cpp
double getYield(const Models::FMTmodel& p_model,
                          const std::string& p_mask,
                          const std::string& p_yield,
                          int age p_age) const;
Utiliser FMTyields dans FMTmodel pour obtenir le yield et utiliser vector<FMTtheme> et FMTmask pour générer un FMTmask avec p_mask.

Ne pas oublier de faire une fonction:
std::vector<std::string> getAttributes(const Models::FMTmodel& p_model,int p_theme) const;
Qui va chercher les attributs du thème p_theme avec le vector<FMTtheme>

Ajouter un UnitTestFMTForm dans UI/tests pour tester les fonctions!

**Comment by bouto3** [comment]
Ajouter une fonction de validation de la présence des yields dans le Model.
En entré:
  -le model 
  -une liste de string yield
En retour :
  -La liste des yields absent si possible

**Comment by bouto3** [comment]
Ajouter une fonction ObtenirNombreAgeMax, voir le détail avec Guillaume :)

**Comment by martel21324** [comment]
Les ligne suivante on été ajouté au header FMTForm.h
ligne 65 --> double getYield(const Models::FMTmodel& p_model, const std::string& p_mask, const std::string& p_yield, int p_age);
ligne 66 --> std::vector<std::string> getAttributes(const Models::FMTmodel& p_model, int p_theme);

Je regarde comment ajuster le .cpp 
(Les updaptes sont sur la brannche #224)

**Comment by martel21324** [comment]
la fonction getActionsNames est terminé, j'étais dans le champ avec mon précédent message finalement ça ressemble plus à cela: System::Collections::Generic::List<System::String^>^ getActionsNames(int p_modelIndex);

**Comment by martel21324** [comment]
Pour me clarifier les idées:

À vérifier:
getActionsNames(int p_modelIndex) --> List<String^>^

À exposer dans le wrapper non fait:
getYields(int p_modelIndex) --> List<String^>
ObtenirNombreAgeMax() ???

Pour utiliser indirectement (Non exposé au Wrapper)
getYield(Models::FMTmodel& p_model, std::string& p_mask, const std::string& p_yield, int age p_age) --> double

**Comment by gcyr** [comment]
getYields () voir Core::FMTyields::getallyieldnames()

getYield(int p_modelIndex,String^ p_mask, String^ p_yield, int p_age) --> double
donc utiliser Core::FMTdevelopement() à l'aide de Core::FMTmask(p_mask) afin de créer un développement après constuire un FMTyieldrequest (méthode dans FMTdeveloppement) ensuite utiliser FMTyields::get(request,p_yield) -> double

**Comment by gcyr** [comment]
Core::FMTdevelopemen::setage(p_age)

**Comment by gcyr** [comment]
ObtenirNombreAgeMax() itéreer sur FMTyields ensuite appeller sur pointeur getlastbase() et conserver le plus gros chiffre et renvoyer!

**Comment by martel21324** [comment]
getArttribute(indexScenario, indexTheme) -> list(string)

**Comment by Landry-G** [comment]
- [ ] Faire une fonction
- [x] faire un getAttributes
- [ ] Ajouter un test dans UI/tests
