### ISSUE TITLE
Composition d'output et type de sources

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#227]
Erreur        : 295, Ligne numéro(52),dans le fichier .\22_REGL_PROV_AVSP_P1_VALID_SANSSEQ.OUT 
                ? ? ? GSR0015 ? REG ? REGINCEXTI ? ? ? ? ? ? ? ? ? ? ? ? @AGE(3)  _INVENT _AREA * 
                1.000000
                Définition d’output invalide OSUPEDUNAT_2_T100%. La combinaison d’une action et de l’inventaire 
                dans la *Source n’est seulement permise que si les outputs utilisés ont été préalablement définis.

L'erreur dit qu'on n'a pas le droit de combiner des sources de type action avec des sources de type inventaire. 
Dans FMToutput::operator std::string() on doit alors détecter ce cas de figure et créer des outputs temporaire inventaire et actions qu'on aditionne par la suite ensemble avec le symbol '+'. Voir FMToutputsource::gettarget() pour différencier les types de sources. Ajouter un test pour cet aspect et s'assurer que les tests testmodelwriter.cpp passent bien.

**Comment by gcyr** [comment]
Afin de splitter un output on doit itérer sur les FMToutputsource de cet output. On fractionne la liste de FMToutpoutsource et FMToperator en plusieurs sous listes (différents outputs). Pour déterminer comment splitter la liste de FMToutpoutsource voir la fonction FMToutpoutsource::isinventory() quand la fonction retourne true on ne peut pas aggréger ces FMToutputsurce avec FMToutputsurce que la fonction isinventory() retourne false. Un coup qu'on réussie à bâtir des sous listes de FMToutputsource et FMToperator qui font du sens, On utilise le constructeur FMToutput(const std::string& lname, const std::string& ldescription,
	const std::string& lgroup,
	const std::vector<FMToutputsource>& lsources,
	const std::vector<FMToperator>& loperators); Pour constuire les sous outputs du output. Ensuite écrire ces sous outputs en string avant notre output. Par la suite pour l'output qui nous intéresse l'écriture est sous la forme *OUTPUT blabla *SOURCE sous_output1 + sous_output2

**Comment by Landry-G** [comment]
Trouver une manière de séparer les types de outputs pour les passer séparément 

-Faire un test en premier

**Comment by Landry-G** [comment]
From branch Issue_227v2
