### ISSUE TITLE
Exposer au Wrapper testActionsBuilder

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#228]
Exposer le modificateur TBE qui est la fonction FMTmodel nouveau = FMTmodel::buildAction(string action_name,string yield_name) générer la nouvelle cédule avec  nouveau.buildSchedule(*nouvea.actions.begin(),vielle_schedule) et ensuite l'écrire pour plus de détail voir testActionsBuilder.cpp.

**Comment by gcyr** [comment]
Faisable à partir de 37e1036

**Comment by martel21324** [comment]
On dois créer un namespace logic ou nommé autrement afin de séparer la logique métier utilisateur du wrapper de l'api.

**Comment by Landry-G** [comment]
Namespace dans un autre issue #235
