### ISSUE TITLE
Erreur dans la documentation de base pour décrire FMT

### ISSUE THREAD

**Issue by JFCarle** [Bureau-du-Forestier-en-chef/FMT#24]
**La phrase originale:**

Le projet FMT a débuté en 2017, à la Direction forestière en chef (BFEC) de Québec.

Correction proposée:

Le projet FMT a débuté en 2017, au Bureau du Forestier en Chef (BFEC) du Québec.

**Comment by BrunoForest** [comment]
C'est quoi l'URL complet de l'endroit ou se trouve cette phrase. Je ne la trouve pas dans la docs actuel.

**Comment by JFCarle** [comment]
[Intranet logo]
https://bureau-du-forestier-en-chef.github.io/FMTdocs/docs/basics/

Jean-François Carle, ing.f., M.Sc.F.
Coordonnateur à l'innovation
Direction du calcul et des analyses (DCA)
Bureau du Forestier en chef
195, boul. Perron-est
Caplan (Québec) G0C 1H0
Tél. :  (418) 388-2125 poste 298
télec. :  (418) 388-2444

***@***.******@***.***>

Ce message est confidentiel et ne s'adresse qu'au destinataire.  S'il vous a été transmis par mégarde, veuillez le détruire et nous en aviser aussitôt. Merci !

De : BForest ***@***.***>
Envoyé : 5 avril 2022 14:20
À : Bureau-du-Forestier-en-chef/FMT ***@***.***>
Cc : Carle, Jean-François (FEC) ***@***.***>; Author ***@***.***>
Objet : Re: [Bureau-du-Forestier-en-chef/FMT] Erreur dans la documentation de base pour décrire FMT (Issue #24)


C'est quoi l'URL complet de l'endroit ou se trouve cette phrase. Je ne la trouve pas dans la docs actuel.

-

**Comment by BrunoForest** [comment]
![image](https://user-images.githubusercontent.com/46934638/161824081-ce65e867-88c7-46ab-be3d-7af5b4da2186.png)
![image](https://user-images.githubusercontent.com/46934638/161824195-df8c9e6c-fd75-4a83-b0cd-54fed48cbee4.png)

Ça semble correct en français et anglais non ?

**Comment by JFCarle** [comment]
Finalement, il n'y avait pas d'erreur. C'est un code 18 :-)
