### ISSUE TITLE
Erreurs dans les Tests TBE

### ISSUE THREAD

**Issue by BFECLucasMoreau** [Bureau-du-Forestier-en-chef/FMT#241]
Donc si je résume après des tests sur les scenarios 30_ReglProv_avsp et 50_StrProdBois_avsp d'un modèle à Michel Caron (T:\Donnees\Usagers\CARMI5\2024_07_Methodes_28_33\Prototype_Dec2023_MethodeTBE) :
 
**Transformation**  : Pas d'erreur apparente dans la console quand j'éxécute.
![Capture_FMT_Transformation](https://github.com/user-attachments/assets/016c7b21-a451-4bfa-a2a4-d05ca13eca21)

**Rastérisation** (14.44 hectares) : j'obtiens cet élément en rouge = "levé une exception"  mais j'ai tout de même un succés de rastérisation au final ...
![Capture_ErrorFMT_Rasterisation](https://github.com/user-attachments/assets/6f545fae-24cd-4a86-b147-08ff011365b4)

**Spatialisation** : Erreur (Horizon de simulation ne variant que de 1 à 0), je ne peux pas lancer la spatialisation et j'ai le message suivant dans la console :
![Capture_FMT_Spacialisation1](https://github.com/user-attachments/assets/f3412ab0-6e14-4b8d-9551-f3d13de8e8ee)

**Comment by gcyr** [comment]
@BFECLucasMoreau peux-tu passer le modèle après transformation et sortir les messages d'erreurs dans WS? ou FMT?

**Comment by BFECLucasMoreau** [comment]
Voir issue #243 pour WS

**Comment by martel21324** [comment]
Aucune erreur dans la rastérisation dans la version 1.3.0.8 avec ces données:
![image](https://github.com/user-attachments/assets/01c0fd3d-3106-4bd0-b8be-3acf1118a653)

**Comment by Landry-G** [comment]
Résolu par #243
