### ISSUE TITLE
Erreur(s) Woodstock dans exécution d'un modèle transformé par FMT (TBE)

### ISSUE THREAD

**Issue by BFECLucasMoreau** [Bureau-du-Forestier-en-chef/FMT#243]
Je lance le modèele en simple flèche dans Woodstock (2021.03, à jour ?!) :

Erreur        :  61 Impossible de trouver le mot-clé CONTROL dans le fichier primaire TEST_TBE_CPF.pri.

**Comment by gcyr** [comment]
Fait juste t'en créer un à la main voir prend en un d'un autre modèle

**Comment by gcyr** [comment]
Même chose du côté de spatialisation:
Au niveau de la syntaxe qui ne passe pas dans WS: Les doublons évidemment, pour les outputs, il ne semble pas vouloir prendre deux multiplications dans la source (YV_S  * YSPB * 0.8 (correct si enlève YSPB) et finalement dans la sections optimize _MAX (OVOLTOTREC_YP23) 1.._LENGTH (il faut enlever les parenthèses) .
