### ISSUE TITLE
Aggrégation d'actions donne une cédule vide

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#247]
Le fichier .seq écrit par la transformation d'aggrégation est vide même si l'utilisateur fourni une cédule avec son modèle. Il y a bien un fichier .seq d'écrit mais on ne retrouve aucune ligne. Pourtant dans le test les fichiers .seq après transformation sont plein.

**Comment by martel21324** [comment]
Pour reproduire le bug j'ai entré les même donné que le test testActionsAggregations dans l'interface comme suit:
Il n'y a pas de test du wrapper encore.
![image](https://github.com/user-attachments/assets/74d046a7-aad5-4001-b9ad-3c70080bd8f1)

**Comment by martel21324** [comment]
Problème résolu, il se trouvais aussi dans Wrapper::FMTForm::splitActions
ModelParser.write écrasait le .seq déjà écrit par SCHEDULE_PARSER.write
Il est important de ne pas changé l'ordre car modelParser en écrit une vide

**Comment by martel21324** [comment]
Ajout d'un test fonctionnel testWrapperAggregatesAllActions et ajout de celui-ci dans bfectest et publié sur Atrhemis
