### ISSUE TITLE
Replanif sur les poste Amazon conccurentrun

### ISSUE THREAD

**Issue by martel21324** [Bureau-du-Forestier-en-chef/FMT#253]
L'interface 1.3.08 lors de la replanification sur les postes amazons sort l'erreur suivante:
![image](https://github.com/user-attachments/assets/86a64653-7a67-4ce4-af47-9871ca0edb57)
J'ai fait essayer à Lorena un seul thread en ajustant le nombre de processus a 1 et nous avons le même message d'erreur.
J'ai vérifié s'il y avait pas quelques chose d'évident a corriger entre les version fonctionnels et celle-ci et rien ne m'a sauté au yeux. Peut-être un problème de mémoire...

Pour la version 1.3.06_replanif, le liens entre l'interface et les dlls semble brisé, aucune donné n'apparait dans tous les onglets. Cela fait ça sur le poste virtuel MV-FEC-P37 et le  poste aws: SEAWS3D mais c'est fonctionnel sur le poste de Lorena. J'ai dit a Dom et Lorena de ne pas passer trop de temps dessu et je n'ai pas consacré de temps non plus la dessu étant donné que la version 08 fonctionne. Je ne sais juste pas si les nouveau développement de Guillaume pour la performance des postes amazon sont dans la 08. 

![image (1)](https://github.com/user-attachments/assets/1cedca2c-ff19-49a1-8cd7-d7ad24fbd2b3)

Je mets en priorité normal car Jean ne voulais pas mettre l'emphase la dessu mais que les poste amazon on les a jusqu'a fin semptembre.

**Comment by gcyr** [comment]
l'option produire solution n'est pas coché par l'utilisateur et pourtant il semble essayer d'en produire une...c'est pas normal.

**Comment by gcyr** [comment]
Ça fonctionne pas non plus sur un poste non Amazon avec la version 1.3.0.9
![image](https://github.com/user-attachments/assets/52260e17-a7d8-4f1d-b3d7-e8d899cbb402)
Mais le test fonctionne bien...

**Comment by gcyr** [comment]
Ligne 68 dans FMTparallelwriter.h const std::string& m_outputLocationPath dit être changé en std::string m_outputLocationPath.

**Comment by gcyr** [comment]
Dans FMTreplanningtask.cpp ligne 96 changer m_primaryName = (m_outputlocation.find_last_of('/') == std::string::npos) ? m_outputlocation : m_outputlocation.substr(m_outputlocation.find_last_of('/') + 1); pour m_primaryName = boost::filesystem::path(m_outputlocation).stem().string();

**Comment by martel21324** [comment]
Les modification sont faite sur le dev avec com ce issue
