### ISSUE TITLE
Création de scénario de réplicats distinct 

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#257]
Lorsqu'on écrit les sédules durant le replanning lorsque le replanning se termine on devrait placer chacun de c'est scedule dans des scénarios réplicat distinct (contenant une section optimize sans exclude sur les actions).

Cella permettra de faire du playback à plusieurs réplicats.

**Comment by gcyr** [comment]
Pour réaliser ça il fait que le fichier schedule soit écrit dans un dossier portant le même nom que le fichier schedule parl la suite le fichier schedule soit renommé au nom du fichier primaire et sous l'extension ._seq. Ensuite créer un fichier ._opt vide dans chaque dossier.

**Comment by martel21324** [comment]
Implémentation réussis.
Un réplicat 0 apparait et pas de replicat 3, a vérifier.
Optimisation a faire!?
