### ISSUE TITLE
S'assurer du lien de la documentation Doxygen avec R et Python

### ISSUE THREAD

**Issue by gcyr** [Bureau-du-Forestier-en-chef/FMT#36]
Valider quelle classes ne possède pas de documentation en Python et en R et apporter les correctifs au code d'exportation ou à la documentation des classes afin que celles-ci soient bien exportées.

**Comment by BrunoForest** [comment]
Fonctionne depuis un certains temps, la documentation suit bien dans le dossier PYNRinclude.
