### ISSUE TITLE
Ajouter les headers précompiler au build 

### ISSUE THREAD

**Issue by BrunoForest** [Bureau-du-Forestier-en-chef/FMT#51]
[target_precompile_headers — CMake 3.23.1 Documentation](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html)

Dans le dossier : build/release/Libincludes

**Comment by BrunoForest** [comment]
Ajouter toutes les headers des dossiers include du projet pour la lib avec une fonction du genre glob recurse *.h

**Comment by gcyr** [comment]
Pour s'assurer de ne pas importer des headers de FMT qui sont seulement utilisé dans les .cpp seulement les .hpp qui comprennent le préprocesseur FMTEXPORT

**Comment by BrunoForest** [comment]
Pas nécessaire on a trouver une autre manière.
